### ISSUE TITLE
Simulator doesn't work

### ISSUE THREAD

**Issue by simon88** [platypii/ParaDrone#3]
HI,
I'm trying to use the simulator but it's doesn't work, first of all `npm start` doesn't work I've to used `npx http-server -c-1`instead. After thaht when I go to `localhost`I have an error in the console `[2022-11-02T08:37:39.419Z]  "GET /js/main.js" Error (404): "Not found`

**Comment by platypii** [comment]
The commands to run the simulator locally are:

```sh
npm i
tsc
npm run serve
```

Looks like I need to update the README. Thanks for letting me know!

**Comment by simon88** [comment]
Thanks, no worries :)
There is always an error when the server run localy
`[2022-11-04T22:20:18.401Z]  "GET /js/main.js" Error (404): "Not found"`
