### ISSUE TITLE
Heltec LoRa V3 compatibility

### ISSUE THREAD

**Issue by cbvicious** [platypii/ParaDrone#5]
Any guidance on what steps to take to make this project compatible with V3? It seems nigh impossible to find V2 boards now.

**Comment by platypii** [comment]
I already have a branch working with the Heltec V3 boards:
https://github.com/platypii/ParaDrone/tree/heltec-v3

Hopefully you should just be able to switch to that branch. If you run into issues feel free to ask questions. I made a writeup on the heltec forum about my experience migrating from V2 to V3:
http://community.heltec.cn/t/heltec-board-migration-from-v2-to-v3/12667

**Comment by cbvicious** [comment]
Ah man. I apologize, I probably saw that when I was first digging through the repo and forgot about it. I'll give that a try this week, but I'll close this for now. 
Note to self: always check the branches when you find what feels like an edge case.
